$ starcluster start physicscluster
>>> Starting cluster...
>>> Launching a 2-node cluster...
>>> Launching master node...
>>> Launching worker nodes...
>>> Waiting for cluster to start...
>>> The master node is ec2-123-12-12-123.compute-1.amazonaws.com
>>> Attaching volume vol-99999999 to master node on /dev/sdz ...
>>> Setting up the cluster...
>>> Mounting EBS volume vol-99999999 on /home...
>>> Creating cluster user: myuser
>>> Configuring scratch space for user: myuser
>>> Configuring /etc/hosts on each node
>>> Configuring NFS...
>>> Configuring passwordless ssh for user: myuser
>>> Installing Sun Grid Engine...
